# Generated by Django 6.0.2 on 2026-03-31 00:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('on_track', 'Dans les temps'), ('at_risk', 'À risque'), ('behind', 'En retard'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='on_track', max_length=20)),
                ('visibility', models.CharField(choices=[('organization', 'Organisation'), ('team', 'Équipe'), ('private', 'Privé')], default='organization', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='organizations.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_goals', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goals.goal')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='organizations.team')),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_comments', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goals.goal')),
            ],
            options={
                'verbose_name': 'Commentaire objectif',
                'verbose_name_plural': 'Commentaires objectifs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('number', 'Nombre'), ('percentage', 'Pourcentage'), ('currency', 'Montant'), ('boolean', 'Oui/Non')], default='number', max_length=20)),
                ('start_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(blank=True, help_text='Ex: clients, FCFA, %, contrats', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='goals.goal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_key_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat clé',
                'verbose_name_plural': 'Résultats clés',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeyResultUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='goals.keyresult')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kr_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mise à jour KR',
                'verbose_name_plural': 'Mises à jour KR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Responsable'), ('contributor', 'Contributeur'), ('viewer', 'Observateur')], default='contributor', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre objectif',
                'verbose_name_plural': 'Membres objectifs',
                'unique_together': {('goal', 'user')},
            },
        ),
    ]
